### ISSUE TITLE
Mapa mental Gilberto Velasco Osorio 

### ISSUE THREAD

**Issue by gilbertovelasco1** [SistemasTecTlaxiaco/actividad-1-mapa-mental-gilbertovelasco1#1]
[Mapa mental Gilberto Velasco Osorio.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-gilbertovelasco1/files/9508782/Mapa.mental.Gilberto.Velasco.Osorio.pdf)

**Comment by josealfredo79** [comment]
Falta la calificacion

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica tiene  15%

**Comment by josealfredo79** [comment]
Revisado..

**Comment by Blanca-estela-valerio-rivero** [comment]
La calificación es 16 %
